### ISSUE TITLE
docs: create a readme for each tooling usage to onboard new members

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#1]
We need someone to show a general panorama of how the following tools are used in the project:

- Github
- VisualCode
- Figma
- Canvas
- MIRO
- Discord

You can contribute by providing a README.md file for each of the tools.

**Comment by Guboehm** [comment]
I'm interested in this task

**Comment by 0xneves** [comment]
Could you add the demo video in the README as well?

**Comment by 0xneves** [comment]
Could you also add a section showing the extensions we are using in for Visual Code as well as the node version we are currently in ( in the repository section)

**Comment by 0xneves** [comment]
Could you also add the live demo please?
https://web3task-front.vercel.app/

**Comment by Guboehm** [comment]
Changes done #13

**Comment by 0xneves** [comment]
Awesome @Guboehm !

**Comment by 0xneves** [comment]
Closing this issue
