### ISSUE TITLE
Submit the grant Proposals to at least 2 leads

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#10]
We have almost everything ready to show and gather grants to keep building the protocol.

Proposal:
- Build a grant/submit proposal using the content on: 
https://github.com/w3b3d3v/web3task-org/blob/main/README.md
- Submit to at least 2 leads

**Comment by viniblack** [comment]
Now it's the moon, let's make it happen 🚀

**Comment by viniblack** [comment]
I'm creating a [doc](https://docs.google.com/document/d/1n_sRyRv51pGDZpr1YE9YDpn623MCwhwaOWfRpBmk8QQ/edit?usp=sharing) to organize and centralize the ideas I want to submit for a grant.

**Comment by 0xneves** [comment]
Wow @viniblack Thank you, it is also very well written!! I didn't find anything that differs from the project goal to comment on! Ride on! Let me know if you need anything!

**Comment by 0xneves** [comment]
Hey @viniblack I found another lead!!!
https://flow.com/flow-grants

Let's go!

**Comment by viniblack** [comment]
I'm also considering applying for the dfinity grant:

https://dfinity.org/grants
https://dfinity.org/community-grants

**Comment by 0xneves** [comment]
This was finished and new issues for the grants was made. Closing this and following in #22
