### ISSUE TITLE
Questions that are unclear

### ISSUE THREAD

**Issue by viniblack** [w3b3d3v/web3task-org#12]
While organizing the [project for the submit grant](https://github.com/w3b3d3v/web3task-org/issues/10)#10 , I came across some questions that I couldn't find the answers to in the existing materials.
And I think they're questions we're going to have to answer eventually.

**Comment by viniblack** [comment]
1. Do we really need outside capital to keep growing? Can we not continue to grow with our current capital?

**Comment by viniblack** [comment]
2. In short, what problems does Web3Task solve? How does it solve them? And what are the revenue sources?

**Comment by viniblack** [comment]
3. Who is our persona? Who is our target audience?

**Comment by viniblack** [comment]
4. What stage is Web3Task in (idea, validation, operation, traction)?

**Comment by viniblack** [comment]
5. What are the project's current expenses and revenue sources?

**Comment by viniblack** [comment]
6. What is Customer Acquisition Cost (CAC)?

**Comment by viniblack** [comment]
7. What is the return on investment (ROI)?

**Comment by Guboehm** [comment]
At the moment it doesn't make sense for the project
