### ISSUE TITLE
Next steps by February 2024

### ISSUE THREAD

**Issue by viniblack** [w3b3d3v/web3task-org#15]
We sat down with the team to define the next steps and set some **goals for February 2024**:

- [ ] Create a landing page with all the key project information; (@heronlancellot @viniblack @durdsvianna)
- [ ] Implement the following in the contracts; (@0xneves @Guboehm)
    - [ ] Contribution system;
    - [ ] Bidding system;
    - [x] Customize the testnet so that everyone can perform all actions;
- [x] Finish the project documentation in the gitbook; (@RafaDSan)
- [x] Finish v2 of the design; (@0xneves @andressa-cabral)
- [ ] Finish v2 of dapp using nextjs and tailwind and implement v2 of design; (everyone)

**Comment by Guboehm** [comment]
The landing page is delivered in https://staging.web3task.w3d.community.
It's missing Contribution system and Bidding system.
