### ISSUE TITLE
feat: create a personalized divisor for Web3Task conten on the LP

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#16]
These dividers are present in the entire LP between contents:
![Image](https://github.com/w3b3d3v/web3task-org/assets/90667119/350101fd-fff0-4742-bb02-5a96c79341a8)

Create one of our own using Web3Task concepts from the logo and publish it here in these comments, also leaving examples grouped in Figma.

**Comment by 0xdev3dl** [comment]
![divisórias](https://github.com/w3b3d3v/web3task-org/assets/101841063/a9e7e40c-520a-4ace-8c26-f427fd3555da)
logo colors in straight line and diamond shape

**Comment by 0xneves** [comment]
Awesome work @andressa-cabral
