### ISSUE TITLE
feat: add Web3Task partners into the following section

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#17]
Add Web3Task partners and hackathon prizes as our partners, such as LaChain, Brainy, Web3Dev, MetaMask, SubGraph, Polygon

![Image](https://github.com/w3b3d3v/web3task-org/assets/90667119/70d7656c-99cd-4f10-82a3-87d81f8b8537)

**Comment by 0xdev3dl** [comment]
![parceiros](https://github.com/w3b3d3v/web3task-org/assets/101841063/63f20b8c-0481-473a-9a93-89030ccf48a4)
I couldn't find ''SubGraph''

**Comment by viniblack** [comment]
> ![parceiros](https://private-user-images.githubusercontent.com/101841063/285674825-63f20b8c-0481-473a-9a93-89030ccf48a4.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDg4MzgsIm5iZiI6MTcwMTEwODUzOCwicGF0aCI6Ii8xMDE4NDEwNjMvMjg1Njc0ODI1LTYzZjIwYjhjLTA0ODEtNDczYS05YTkzLTg5MDMwY2NmNDhhNC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxODA4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDVjYTljMzliYTdjY2I1ZDI1NGM1YTVkOGY0NzBmYzM0NTYwZDRmNGU1MTRlNjdjODdkOWJiNDczZDBmOGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n0H7ZB9EwfMETLXGNGpw_ssJsbrzv58QOymDViNjFtY) I couldn't find ''SubGraph''

If you're looking for the SubGraph logo, search for "The Graph", the platform that allows you to create subgraphs.

**Comment by 0xdev3dl** [comment]
![image](https://github.com/w3b3d3v/web3task-org/assets/101841063/b9b7106a-e8b6-4e8a-89b8-38796291f488)
Done

**Comment by 0xneves** [comment]
Could you separate them in groups for latter svg extractions? The devs need to place them in a carrousel like. When aligned with displacement between them, they should have around 150% of the width of the screen.

**Comment by 0xneves** [comment]
Will close this as we are going to use as a carrousel eventualy
