### ISSUE TITLE
feat: add the Web3Task features from the pitch into the section

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#19]
Our pitch has a lot of information about the project, add those features into the following section. Focus on selling our product:
![Image](https://github.com/w3b3d3v/web3task-org/assets/90667119/bc61df39-e75f-4b93-93e3-82c2c845959a)

The pitch is here: https://www.canva.com/design/DAFxSNipyGo/n1CFy1HHW04Lf1fcublKRg/edit?utm_content=DAFxSNipyGo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by 0xdev3dl** [comment]
![roadmap 1](https://github.com/w3b3d3v/web3task-org/assets/101841063/e77ccfd2-4b56-453d-8fcc-ab602c330520)
standardization of LP colors

**Comment by 0xneves** [comment]
> Our pitch has a lot of information about the project, add those features into the following section. Focus on selling our product: ![Image](https://private-user-images.githubusercontent.com/90667119/285325073-bc61df39-e75f-4b93-93e3-82c2c845959a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5OTk4NzcsIm5iZiI6MTcwMTk5OTU3NywicGF0aCI6Ii85MDY2NzExOS8yODUzMjUwNzMtYmM2MWRmMzktZTc1Zi00YjkzLTkzZTMtODJjMmM4NDU5NTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxMzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYmI2OGUxZTY2NjJkZmU1NjVkMzU2NWEwMTdhMmYxMmI0MzAyMDM1ZTYxODBiNDVmYTE3OTE0NmYzMGEzZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pv5DsFAPm8LPmDFFa8DXeiJzHOXNoXpYr1jABICdFSA)
> 
> The pitch is here: https://www.canva.com/design/DAFxSNipyGo/n1CFy1HHW04Lf1fcublKRg/edit?utm_content=DAFxSNipyGo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

We are looking to change the texts on the above picture into the features of Web3Task, like the content on these:
![image](https://github.com/w3b3d3v/web3task-org/assets/90667119/e51f278e-6b17-4aac-a219-af05739e195e)

**Comment by 0xdev3dl** [comment]
![image](https://github.com/w3b3d3v/web3task-org/assets/101841063/166a5cbb-c557-4c16-885e-2099aef1fb96)
Done.
