### ISSUE TITLE
chore: publish hackathon results on PodLabs

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#21]
We just won the hackathon and we need to shill a little bit!
Please post a brief about what happened on the PodLabs channel on Discord as well as in the general chat.

Then share the link here in this thread.

**Comment by annabida** [comment]
https://discord.com/channels/898706705779687435/898706706224250890/1179228894130356295

https://discord.com/channels/898706705779687435/1018684397265883216/1179223909250375720

**Comment by 0xneves** [comment]
Thank you so much @annabida :D
