### ISSUE TITLE
Roadmap design change

### ISSUE THREAD

**Issue by 0xdev3dl** [w3b3d3v/web3task-org#24]
In the revision of the LP design, we agreed to put the design on the S model, with more distributed information for the scroll bar.
![image](https://github.com/w3b3d3v/web3task-org/assets/101841063/e9d986a3-5b35-4674-a595-838ceab00ab7)

**Comment by 0xdev3dl** [comment]
It looks like this
![image](https://github.com/w3b3d3v/web3task-org/assets/101841063/c97ce1f5-4405-4566-8b43-dec91dc51ecb)

**Comment by 0xneves** [comment]
Nice!
