### ISSUE TITLE
King Of Devs 1.0 Brasil Hackathon Prizes 

### ISSUE THREAD

**Issue by viniblack** [w3b3d3v/web3task-org#25]
As we reported in issue #14, we managed to win in all three categories we competed in at King Of Devs 1.0 Brasil and have already received some of the awards:

- [x] - Brainy’s Path Track - [500 USD](https://bscscan.com/tx/0x1ee2601fbb9d66a28b32fb4d400b57de7dfe13e330d00ad898d817ecfbdd5e8b)
- [x] - Track #LaChain - [1000 USD](https://polygonscan.com/tx/0xe5a5926e5d8cb6cf85521e8d1121900b95663b8095f85ee545ff73e3164f071a)
- [ ] - Track Speezard: FREE INCUBATION by [Speezard](https://www.speezard.io/)

**Comment by viniblack** [comment]
The **Track #LaChain** I'm in contact with LaChain support as they recommended receiving it through Ripio because the prize was in LAC and I found it difficult to use the platform to send the prize to the project's wallet.

**Comment by Guboehm** [comment]
Prizes have been received, thank you
