### ISSUE TITLE
style: roadmap review

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#27]
Proposal:
- Font-size 16px
- Green color on task achieved should be the same blue as the non-achieved, but filled in the middle
- Change dates to be on the side and to me measured in Quarters (Q1, Q2, Q3, Q4)
- Discuss with @0xneves the content of the roadmap (texts inside the cards)
- Color pallete should be the same as the rest of the app
- Remove italic feature

**Comment by 0xdev3dl** [comment]
![image](https://github.com/w3b3d3v/web3task-org/assets/101841063/89544219-2937-43ab-92b3-d3f21b1011bf)
Font-size 16px ✅
Change dates ✅
Color pallete ✅

**Comment by 0xdev3dl** [comment]
@0xneves let's discuss the roadmap text

**Comment by 0xneves** [comment]
Since this is just a matter of "text" and the roadmap is still changing a little bit, we will do this in the future as there are other priorities right now, but we will do this as soon as possible! Moved to inprogress as I still need to contribute to the texts.

**Comment by 0xneves** [comment]
Bumping this for myself!

**Comment by Guboehm** [comment]
We agree with the style, lets close the issue and discuss the topics later.
