### ISSUE TITLE
Raise displacement between screens

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#28]
Title is describing it well, we must raise a discrepancy

![Image](https://github.com/w3b3d3v/web3task-org/assets/90667119/1f0f174c-dc54-471d-8661-d10d0782b01c)

**Comment by 0xdev3dl** [comment]
![image](https://github.com/w3b3d3v/web3task-org/assets/101841063/ec6bd1a4-f058-433e-9609-515ace619205)
adjusted spacing ✅
