### ISSUE TITLE
chores: prepare milestones of the year for final report

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#31]
Proposal:

- Define documentation in README.md file and open a pull request resolving this issue, this is how we will keep this task updated.
- Track our footprints since May 2023 when the Hackathon started as the solving issue for the lack of funds for contributors.
- Follow up all the hirings and debates, deliver and changes that lead us to the open-source incentivized product that wins a hackathon.
- Use a chronological approach (timeline) and comment on difficulties, superations, and skills collected and content aggregated to Web3Dev.
- Collect feedback from all members on what they learned and how Web3Task enhanced their professional careers.
- Collect the analytics from GitHub for all repositories for which Web3task was responsible. Don't forget the hackathon repository!
- Please do use the creativity to propose more cool stuff for this final yearly report!

**Comment by 0xdev3dl** [comment]
Working on the report, follow up: https://www.canva.com/design/DAF5lUfd04s/R__j3HSHBO8wyseokdkPog/edit?utm_content=DAF5lUfd04s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by 0xneves** [comment]
> Working on the report, follow up: https://www.canva.com/design/DAF5lUfd04s/R__j3HSHBO8wyseokdkPog/edit?utm_content=DAF5lUfd04s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Wow @andressa-cabral This is amazing!! Congratulations!

**Comment by Guboehm** [comment]
I spoke with @andressa-cabral  and we agreed to add a brief summary of the report, list the main topics in the ReadMe and reference the link to the final delivery.

**Comment by 0xneves** [comment]
> I spoke with [@andressa-cabral](https://github.com/andressa-cabral) and we agreed to add a brief summary of the report, list the main topics in the ReadMe and reference the link to the final delivery.

Since the format is in Word A4 format and not Github markdown it will be a better approach! Ride on!

**Comment by Guboehm** [comment]
OK, let's continue this way @andressa-cabral

**Comment by 0xdev3dl** [comment]
As agreed, here is the final report in markdown located in the web3task-org repository: https://github.com/w3b3d3v/web3task-org/blob/main/Annual%20Report.md
