### ISSUE TITLE
chore: create CONTRIBUTING.md for the community

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#32]
This [link](https://docs.github.com/pt/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) is an example of how to build a guideline for contributing to open-source projects.

This is an [example](https://github.com/angular/angular/blob/main/CONTRIBUTING.md) of Angular and their standard.

Proposal: 
- Write a simple contributing guideline for newcomers to learn how to contribute.
- Submit this file for all web3task repositories as a PR, referring to this issue.

**Comment by viniblack** [comment]
I believe I can help with this need.

**Comment by viniblack** [comment]
I've created the first version for the front repository, after it's approved I'll use this as the basis for the other repositories 

[w3b3d3v/web3task-front/pull/170](https://github.com/w3b3d3v/web3task-front/pull/170)

**Comment by Guboehm** [comment]
@viniblack Your PR for the frontend has been approved.
We are waiting for the PR of the contract repository and landing page.
thanks.

**Comment by Guboehm** [comment]
New update, @viniblack is making the latest adjustments.

**Comment by viniblack** [comment]
PR front: https://github.com/w3b3d3v/web3task-front/pull/171
PR contracts: https://github.com/w3b3d3v/web3task-contracts/pull/55
PR landing page: https://github.com/w3b3d3v/web3task-lp/pull/23

**Comment by Guboehm** [comment]
@viniblack  review prs please

**Comment by Guboehm** [comment]
Done, thanks @viniblack
