### ISSUE TITLE
chore: add linktree of web3task contents in the gitbook

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#34]
@RafaDSan Could you take a look at it?

Proposal:
- Unite all links from the Web3Task project into the GitBook you made!

**Comment by RafaDSan** [comment]
Working on this

**Comment by RafaDSan** [comment]
Linktree, Discord, Twitter, and Dashboard of Web3Task tasks added to the gitbook


![Image](https://github.com/w3b3d3v/web3task-org/assets/102108966/43485841-f2d5-4728-a039-03571c2d06b7)

**Comment by 0xneves** [comment]
Thank you so much @RafaDSan , its perfect!
