### ISSUE TITLE
chore: migrate the web3task gitbook into web3dev ownership

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#35]
Currently, @RafaDSan has ownership over Gitbook, but we need to move this access into Web3Dev ownership.

Proposal:
- Get the template from gitbook
- Create an web3dev account with help of @annabida 
- Help migrate the content into the new gitbook account

**Comment by RafaDSan** [comment]
Working on this!

**Comment by Guboehm** [comment]
This issue was resolved at [Gitbook Web3Task](https://links.w3d.community/web3task/official-documentation/introducing-web3task)
