### ISSUE TITLE
chore: review pitch using new visual identity

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#36]
@viniblack settled the proposal in the next comment

**Comment by viniblack** [comment]
Gather the information that @RafaDSan and I have gathered about the project and apply it to the pitch.
Our current pitch is an MVP that was developed in less than a week, so it is missing some important information about the project.

Meta:
- Rewrite the pitch by the end of January
- Present the pitch at the [web3valley](https://www.web3valley.com.br/) event that takes place in the first week of each month (the idea is to get feedback on the project and the presentation).

**Comment by Guboehm** [comment]
Pitch review is ready.
@viniblack share the link please.

**Comment by Guboehm** [comment]
At the moment it doesn't make sense for the project
