### ISSUE TITLE
Get Theme from other famous dApps

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#9]
Proposal:
- Get Color palette (specially the grays)
- Get images alike
- Kickstart the next version in Figma just creating the page names and their sizes
- - Only dark mode
- - 1920x1080

References:
- https://relay.gelato.network/
- https://app.uniswap.org/swap

Observe the rounded objects and the icons, which are very well separated.
Very few buttons and colors that don't hurt the eyes. Only the buttons have strong colors.

**Comment by 0xneves** [comment]
Have you tried to use the animations in Figma? To show demos of the design to look like the real app?

**Comment by 0xdev3dl** [comment]
I have the images, color palette and icons. I will build 
https://www.figma.com/file/UDGGqo8K53CiYYpGutoVuH/PodLabs?type=design&node-id=1527-1886&mode=design&t=0mBs87y6YVZN2ziN-0

**Comment by 0xneves** [comment]
Can we schedule a meeting to talk about the material you collected @andressa-cabral ?

**Comment by 0xdev3dl** [comment]
Scheduled for 11/23 at 8pm

**Comment by 0xneves** [comment]
We had a conversation and advanced a lot in the design

**Comment by 0xdev3dl** [comment]
LP ready ✅
I've selected some dApp templates in the checkout model
https://app.defisaver.com/
https://app.shellprotocol.io/explore
https://swapr.eth.link/#/swap?chainId=1
